name: Publish to Maven repository 

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      PASSPHRASE:
        required: true
      PUBLISH_USER:
        required: true
      PUBLISH_PASSWORD:
        required: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    - name: Publish
      run: sbt clean publishSigned
      env:
        PUBLISH_USER: ${{secrets.PUBLISH_USER}}
        PUBLISH_PASSWORD: ${{secrets.PUBLISH_PASSWORD}}
