name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Build and test
      shell: bash
      run: sbt -v +test
      
